function object_list = get_objectlist_training()
% get the list of objects you want to use
object_list = {'APPLE', 'BED', 'BLIMP', 'BLOW_DRYER', 'BOOMBOX',...
    'BROOM', 'CAKE_SLICE', 'CAN_OPENER', 'COFFEE_FILTER', 'COIN',...
    'DRILL', 'DUST_PAN', 'ENVELOPE', 'FIRE_HYDRANT', 'FLASH_DRIVE', ...
    'FLASK', 'FOOTBALL', 'FRISBEE', 'HAIR_BRUSH', 'HOUR_GLASS', 'KAYAK',...
    'LAMP', 'LAWN_CHAIR', 'LIGHTER', 'LOAF_OF_BREAD','LUNCH_BOX', ...
    'MATTRESS', 'MEASURING_CUP', 'MICROWAVE', 'PICNIC_BASKET', 'SHORTS',...
    'SODA_BOTTLE', 'SPONGE', 'SQUIRT_GUN', 'STAPLER', 'STOOL', 'SUITCASE',...
    'TEDDY_BEAR', 'TELEVISION', 'TENNIS_BALL', 'TENT', 'TOASTER', 'TOILET',...
    'TRASH_CAN', 'WATERMELON_SLICE'};

end 