function object_list = get_objectlist()
% get the list of objects you want to use
object_list = {'ALARM_CLOCK' , ...
'BOOK','BOWL', ...
'CAKE_PAN' , 'DECK_OF_CARDS' ,'CD' ,'CHEESE_GRATER' , 'CLOCK','GAMING_CONTROLLER','CUP',...
'CUPCAKE_LINERS' , 'CUTTING_BOARD', ...
'DISH_SOAP','DISH_TOWEL', 'DVD_COVER', ...
'EGG_CARTON', ...
 'GLUE_STICK', ...
'HAIRBAND', 'HAT' ,'HELMET', ...
 'JAR_OF_JAM' , ...
'KETCHUP_BOTTLE', ...
'LIQUID_SOAP', ...
'COMPUTER_MOUSE', 'MUSTARD' , ...
'OVEN_MITT', ...
'PEPPER_SHAKER', 'PHONE', 'PILLOW' , 'PLATE' ,'POT', ...
'SANDAL', 'SHAMPOO_BOTTLE', 'BAR_OF_SOAP','STRAINER', ...
'REMOTE_CONTROL' , 'ROLLING_PIN' ,'RULER'...
'TISSUES' ,'TOAST', 'TOILET_BRUSH','TOILET_PAPER',  'TOOTHPASTE' ...
'VASE', ...
'WASHCLOTH'};

end 
